### ISSUE TITLE
Computing the weights

### ISSUE THREAD

**Issue by camigord** [Damcy/prioritized-experience-replay#1]
Hi Damcy, 

thanks a lot for the code. It helped me a lot. 

I have a small comment. In the function **sample** from the file **rank_based.py**, you compute the weights as:

`# w = (N * P(i)) ^ (-beta) / max w`
`w = np.power(np.array(alpha_pow) * partition_max, -beta)`

where N is represented by the variable _partition_max_, defined as:

`partition_max = dist_index * self.partition_num`

My question is, shouldn't N be equal to the memory size? or, in this case, to the partition size? Something like:

` partition_size = math.floor(self.size / self.partition_num)`
`partition_max = dist_index * partition_size `

**Comment by Damcy** [comment]
@camigord yes, I make a mistake here.
partition_size is diff to partition_num. According to your suggestion, the code has been rewritten. Thanks for your issue.

**Comment by camigord** [comment]
Hey, thanks for replying. 
I saw you changed the code, but be careful because **n_partitions** is not defined in that function. You could use **self.partition_num** instead.

**Comment by Damcy** [comment]
ok. Fixed. Thx.
If this part still has bugs, welcome make a pull request :)
