### ISSUE TITLE
why don't you design the batch size just same as the partition number?

### ISSUE THREAD

**Issue by ColdCodeCool** [Damcy/prioritized-experience-replay#2]
Thank you for your excellent work, Damcy!
In build distribution method,  why you choose a larger partition number than the batch size. 

However, in the original paper, the author suggested that we should let the memory partition number just same as the batch size. Could you please help me understand this, Thank you!

**Comment by Damcy** [comment]
Yep. The author suggested that we should let the memory partition number just same as the batch size. And you can set any value of the partition number in these code. It seems no good reason to limit the range of the value.
If you find something difference in the application, please let me know and I will add a suggestion in the readme file.
