### ISSUE TITLE
Code Examples of priority queue in a DQN

### ISSUE THREAD

**Issue by filmo** [Damcy/prioritized-experience-replay#3]
Would you be willing to share a few lines of the NLP DQN code that show the storing of a (s,a,r,s') tuple as well as the portion code where a stored memory is updated with the delta value to change the queue priority for subsequent sampling?

If you have a separate github for the NLP DQN code, I would love to see it. 

Thanks for sharing this priority queue code. It looks well implemented.

**Comment by Damcy** [comment]
The code is released now. The link is https://github.com/Damcy/cascadeLSTMDRL
