### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by raymondchua** [Damcy/prioritized-experience-replay#4]
Hi, I am curious about the execution time when using prioritized experience replay. I have written the rank-bassed prioritization and now it takes a longer time to complete one epoch as instead of using mini-batch, we compute a single sample as time when training the DQN. Any thoughts?

**Comment by Damcy** [comment]
I never compare the performance of the two method. But I think the execution time is depends on the size of replay memory. The operations of the rank-based prioritization will affect the execution time.

**Comment by faaanbingbing** [comment]
你好，如果使用比较大的replay_memory_size，比如10万，100万，是会出现各种索引错误的，请问可以修正吗?

**Comment by Damcy** [comment]
@faaanbingbing 是这份代码有问题吗，可能是分区的部分写得有问题，但是思路应该是ok的，看可以fork过去加工一下，我这边用的没发现明显的bug。
